package trabalhopreenchimento;

import java.awt.Point;
import java.awt.image.BufferedImage;
import java.awt.image.ColorModel;
import java.awt.image.WritableRaster;
import javax.swing.ImageIcon;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author gabrielozaki
 */
public class Visualizador extends javax.swing.JFrame {

    //Imagem a ser manipulada
    BufferedImage imagem = Algoritmos.criaImagem(450, 350);
    //Cópia da imagem original, para podermos restaurar
    BufferedImage original = Algoritmos.criaImagem(450, 350);
    //Pontos da reta
    Point ini;
    Point fim;
    //Verifica se é o primeiro ponto da reta
    boolean primeiroClick = true;
    //Verifica se vai desenhar uma reta ou ponto
    boolean retaponto = false;
    //Classe de algoritmos
    Algoritmos a = new Algoritmos();
    Point p1 = new Point(100, 100);
    Point p2 = new Point(300, 100);
    Point p3 = new Point(300, 300);
    Point p4 = new Point(150, 200);
    //Point p4 = new Point(100, 300);
    Point p5 = new Point(100, 300);
    
    
    
    /**
     * Creates new form visualizador
     */
    public Visualizador() {
        initComponents();
        
        a.desenhaRetaBresenham(this.imagem, p1, p2);
        a.desenhaRetaBresenham(this.imagem, p2, p3);
        a.desenhaRetaBresenham(this.imagem, p3, p4);
        a.desenhaRetaBresenham(this.imagem, p4, p5);
        a.desenhaRetaBresenham(this.imagem, p5, p1);
        ImagemLabel.setIcon(new ImageIcon(this.imagem));
        ImagemLabel.setSize(this.imagem.getWidth(), this.imagem.getHeight());
        ImagemPanel.setSize(this.imagem.getWidth(), this.imagem.getHeight());
    }

    //Copia uma BufferedImage, evitando assim que editemos a imagem original
    //Código de referencia veio daqui:
    //http://stackoverflow.com/questions/3514158/how-do-you-clone-a-bufferedimage
    static BufferedImage clonaImagem(BufferedImage original) {
        //Pega o model das cores
        ColorModel cm = original.getColorModel();
        //Verifica se existe transparencia
        boolean isAlphaPremultiplied = cm.isAlphaPremultiplied();
        //Copia os dados da imagem
        WritableRaster raster = original.copyData(null);
        //retorna a imagem
        return new BufferedImage(cm, raster, isAlphaPremultiplied, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImagemPanel = new javax.swing.JPanel();
        ImagemLabel = new javax.swing.JLabel();
        PosLabel = new javax.swing.JLabel();
        RegioesButton = new javax.swing.JRadioButton();
        RegioesButton.setText("Preenchimento por Regiões");
        FloodButton = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        AcaoMenu = new javax.swing.JMenu();
        OriginalMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ImagemPanel.setBackground(new java.awt.Color(200, 200, 200));
        ImagemPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ImagemPanelMouseMoved(evt);
            }
        });

        ImagemLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ImagemLabelMouseMoved(evt);
            }
        });
        ImagemLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagemLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ImagemPanelLayout = new javax.swing.GroupLayout(ImagemPanel);
        ImagemPanel.setLayout(ImagemPanelLayout);
        ImagemPanelLayout.setHorizontalGroup(
            ImagemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImagemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );
        ImagemPanelLayout.setVerticalGroup(
            ImagemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImagemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
        );

        PosLabel.setText("(0,0)");

        RegioesButton.setSelected(true);
        RegioesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PontoButtonActionPerformed(evt);
            }
        });

        FloodButton.setText("Flood");
        FloodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetaButtonActionPerformed(evt);
            }
        });

        AcaoMenu.setText("Ações");

        OriginalMenu.setText("Original");
        OriginalMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OriginalMenuActionPerformed(evt);
            }
        });
        AcaoMenu.add(OriginalMenu);

        jMenuBar1.add(AcaoMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(ImagemPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(PosLabel)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(RegioesButton)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(FloodButton)))
        			.addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(ImagemPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(FloodButton)
        				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(PosLabel)
        					.addComponent(RegioesButton)))
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OriginalMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OriginalMenuActionPerformed
        // TODO add your handling code here:
        //Aqui usamos o ImagemLabel pq o panel muda de tamanho
        this.imagem = clonaImagem(original);
        ImagemLabel.setIcon(new ImageIcon(this.imagem));

    }//GEN-LAST:event_OriginalMenuActionPerformed

    private void ImagemLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagemLabelMouseClicked
        // TODO add your handling code here:
        if (RegioesButton.getModel().isSelected()) {
            //Insere ponto no label
            ImagemLabel.setIcon(new ImageIcon(a.preencheVarredura(this.imagem, 90, 350, 90, 350)));

        } else {
            ImagemLabel.setIcon(new ImageIcon(a.preencheFlood(this.imagem, evt.getX(),evt.getY())));
        /*    this.primeiroClick = true;
            this.fim = ImagemLabel.getMousePosition();
            System.out.println("Segundo clique:" + this.fim.getX() + "," + this.fim.getY());

            double distancia = a.getDistancia(ini, fim);

            ImagemLabel.setIcon(new ImageIcon(a.desenhaCirculoBresenham(this.imagem, (int) this.ini.getX(), (int) this.ini.getY(), distancia)));*/
        }


    }//GEN-LAST:event_ImagemLabelMouseClicked

    private void ImagemLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagemLabelMouseMoved
        // TODO add your handling code here:
        Point p = ImagemLabel.getMousePosition();
        PosLabel.setText("(" + Math.round(p.getX()) + "," + Math.round(p.getY()) + ")");
    }//GEN-LAST:event_ImagemLabelMouseMoved

    private void PontoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PontoButtonActionPerformed
        // TODO add your handling code here:
        this.retaponto = false;
        FloodButton.setSelected(false);
    }//GEN-LAST:event_PontoButtonActionPerformed

    private void RetaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetaButtonActionPerformed
        // TODO add your handling code here:
        this.retaponto = true;
        RegioesButton.setSelected(false);
    }//GEN-LAST:event_RetaButtonActionPerformed

    private void ImagemPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagemPanelMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ImagemPanelMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visualizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Visualizador().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AcaoMenu;
    private javax.swing.JLabel ImagemLabel;
    private javax.swing.JPanel ImagemPanel;
    private javax.swing.JMenuItem OriginalMenu;
    private javax.swing.JRadioButton RegioesButton;
    private javax.swing.JLabel PosLabel;
    private javax.swing.JRadioButton FloodButton;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
