package trabalhoretacirculo;

import java.awt.Point;
import java.awt.image.BufferedImage;
import java.awt.image.ColorModel;
import java.awt.image.WritableRaster;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author gabrielozaki
 */
public class Visualizador extends javax.swing.JFrame {

    //Imagem a ser manipulada
    BufferedImage imagem = Algoritmos.criaImagem(450, 350);
    //Cópia da imagem original, para podermos restaurar
    BufferedImage original = Algoritmos.criaImagem(450, 350);
    //Pontos da reta
    Point ini;
    Point fim;
    //Verifica se é o primeiro ponto da reta
    boolean primeiroClick = true;
    //Verifica se vai desenhar uma reta ou ponto
    boolean retaponto = false;
    //Classe de algoritmos
    Algoritmos a = new Algoritmos();

    
    
    /**
     * Creates new form visualizador
     */
    public Visualizador() {
        initComponents();
        
        ImagemLabel.setIcon(new ImageIcon(this.imagem));
        ImagemLabel.setSize(this.imagem.getWidth(), this.imagem.getHeight());
        ImagemPanel.setSize(this.imagem.getWidth(), this.imagem.getHeight());
    }

    //Copia uma BufferedImage, evitando assim que editemos a imagem original
    //Código de referencia veio daqui:
    //http://stackoverflow.com/questions/3514158/how-do-you-clone-a-bufferedimage
    static BufferedImage clonaImagem(BufferedImage original) {
        //Pega o model das cores
        ColorModel cm = original.getColorModel();
        //Verifica se existe transparencia
        boolean isAlphaPremultiplied = cm.isAlphaPremultiplied();
        //Copia os dados da imagem
        WritableRaster raster = original.copyData(null);
        //retorna a imagem
        return new BufferedImage(cm, raster, isAlphaPremultiplied, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImagemPanel = new javax.swing.JPanel();
        ImagemLabel = new javax.swing.JLabel();
        PosLabel = new javax.swing.JLabel();
        PontoButton = new javax.swing.JRadioButton();
        RetaButton = new javax.swing.JRadioButton();
        CirculoButton = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        AcaoMenu = new javax.swing.JMenu();
        OriginalMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ImagemPanel.setBackground(new java.awt.Color(200, 200, 200));
        ImagemPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ImagemPanelMouseMoved(evt);
            }
        });

        ImagemLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ImagemLabelMouseMoved(evt);
            }
        });
        ImagemLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagemLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ImagemPanelLayout = new javax.swing.GroupLayout(ImagemPanel);
        ImagemPanel.setLayout(ImagemPanelLayout);
        ImagemPanelLayout.setHorizontalGroup(
            ImagemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImagemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );
        ImagemPanelLayout.setVerticalGroup(
            ImagemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImagemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
        );

        PosLabel.setText("(0,0)");

        PontoButton.setSelected(true);
        PontoButton.setText("Ponto");
        PontoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PontoButtonActionPerformed(evt);
            }
        });

        RetaButton.setText("Reta");
        RetaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetaButtonActionPerformed(evt);
            }
        });

        CirculoButton.setText("Circulo");
        CirculoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CirculoButtonActionPerformed(evt);
            }
        });

        AcaoMenu.setText("Ações");

        OriginalMenu.setText("Original");
        OriginalMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OriginalMenuActionPerformed(evt);
            }
        });
        AcaoMenu.add(OriginalMenu);

        jMenuBar1.add(AcaoMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PosLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PontoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RetaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CirculoButton)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImagemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RetaButton)
                        .addComponent(CirculoButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PosLabel)
                        .addComponent(PontoButton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OriginalMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OriginalMenuActionPerformed
        // TODO add your handling code here:
        //Aqui usamos o ImagemLabel pq o panel muda de tamanho
        this.imagem = clonaImagem(original);
        ImagemLabel.setIcon(new ImageIcon(this.imagem));

    }//GEN-LAST:event_OriginalMenuActionPerformed

    private void ImagemLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagemLabelMouseClicked
        // TODO add your handling code here:
        if (PontoButton.getModel().isSelected()) {
            //Insere ponto no label
            ImagemLabel.setIcon(new ImageIcon(a.desenhaPonto(this.imagem, ImagemPanel.getMousePosition())));

        } else if (this.primeiroClick == true) {
            //Marca que ocorreu o primeiro clique
            this.primeiroClick = false;
            this.ini = ImagemLabel.getMousePosition();
            System.out.println("Primeiro clique:" + this.ini.getX() + "," + this.ini.getY());

        } else if (RetaButton.getModel().isSelected()) {
            //Marca que o primeiro clique deve ser marcado de novo
            this.primeiroClick = true;
            this.fim = ImagemLabel.getMousePosition();
            System.out.println("Segundo clique:" + this.fim.getX() + "," + this.fim.getY());

            //Insere no label
            //ImagemLabel.setIcon(new ImageIcon(a.desenhaRetaParametrica(this.imagem,this.ini,this.fim,1000)));
            ImagemLabel.setIcon(new ImageIcon(a.desenhaRetaBresenham(this.imagem, this.ini, this.fim)));

        } else {
            this.primeiroClick = true;
            this.fim = ImagemLabel.getMousePosition();
            System.out.println("Segundo clique:" + this.fim.getX() + "," + this.fim.getY());

            double distancia = a.getDistancia(ini, fim);

            ImagemLabel.setIcon(new ImageIcon(a.desenhaCirculoBresenham(this.imagem, (int) this.ini.getX(), (int) this.ini.getY(), distancia)));
        }


    }//GEN-LAST:event_ImagemLabelMouseClicked

    private void ImagemLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagemLabelMouseMoved
        // TODO add your handling code here:
        Point p = ImagemLabel.getMousePosition();
        PosLabel.setText("(" + Math.round(p.getX()) + "," + Math.round(p.getY()) + ")");
    }//GEN-LAST:event_ImagemLabelMouseMoved

    private void PontoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PontoButtonActionPerformed
        // TODO add your handling code here:
        this.retaponto = false;
        RetaButton.setSelected(false);
        CirculoButton.setSelected(false);
    }//GEN-LAST:event_PontoButtonActionPerformed

    private void RetaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetaButtonActionPerformed
        // TODO add your handling code here:
        this.retaponto = true;
        PontoButton.setSelected(false);
        CirculoButton.setSelected(false);
    }//GEN-LAST:event_RetaButtonActionPerformed

    private void CirculoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CirculoButtonActionPerformed
        // TODO add your handling code here:
        RetaButton.setSelected(false);
        PontoButton.setSelected(false);
    }//GEN-LAST:event_CirculoButtonActionPerformed

    private void ImagemPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagemPanelMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ImagemPanelMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visualizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Visualizador().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AcaoMenu;
    private javax.swing.JRadioButton CirculoButton;
    private javax.swing.JLabel ImagemLabel;
    private javax.swing.JPanel ImagemPanel;
    private javax.swing.JMenuItem OriginalMenu;
    private javax.swing.JRadioButton PontoButton;
    private javax.swing.JLabel PosLabel;
    private javax.swing.JRadioButton RetaButton;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
