package trabalhocasa3d;

import java.awt.Point;
import java.awt.image.BufferedImage;
import java.awt.image.ColorModel;
import java.awt.image.WritableRaster;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author gabrielozaki
 */
public class Visualizador extends javax.swing.JFrame {

    //Imagem a ser manipulada
    BufferedImage imagem = Algoritmos.criaImagem(500, 500);
    //Cópia da imagem original, para podermos restaurar
    BufferedImage original = Algoritmos.criaImagem(500, 500);

    Casa casa;

    /**
     * Creates new form visualizador
     */
    public Visualizador() {
        initComponents();

        ImagemLabel.setIcon(new ImageIcon(this.imagem));
        ImagemLabel.setSize(this.imagem.getWidth(), this.imagem.getHeight());
        ImagemPanel.setSize(this.imagem.getWidth(), this.imagem.getHeight());

        ArrayList<Ponto3d> Pontos;
        Pontos = new ArrayList<>();

        Pontos.add(new Ponto3d(150, 250, 50));//0
        Pontos.add(new Ponto3d(200, 250, 50));//1
        Pontos.add(new Ponto3d(150, 250, 100));//2
        Pontos.add(new Ponto3d(200, 250, 100));//3
        Pontos.add(new Ponto3d(150, 200, 50));//4
        Pontos.add(new Ponto3d(200, 200, 50));//5
        Pontos.add(new Ponto3d(150, 200, 100));//6
        Pontos.add(new Ponto3d(200, 200, 100));//7
        Pontos.add(new Ponto3d(175, 150, 50));//8
        Pontos.add(new Ponto3d(175, 150, 100));//9
        
        casa = new Casa(Pontos);
        
        ImagemLabel.setIcon(new ImageIcon(casa.projecaoFrontal()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImagemPanel = new javax.swing.JPanel();
        ImagemLabel = new javax.swing.JLabel();
        PosLabel = new javax.swing.JLabel();
        FrontalButton = new javax.swing.JButton();
        CavButton = new javax.swing.JButton();
        anguloText = new javax.swing.JTextField();
        EscalaButton = new javax.swing.JButton();
        EscalaX = new javax.swing.JTextField();
        EscalaY = new javax.swing.JTextField();
        EscalaZ = new javax.swing.JTextField();
        RotacionaX = new javax.swing.JButton();
        RotX = new javax.swing.JTextField();
        RotY = new javax.swing.JTextField();
        RotacionaY = new javax.swing.JButton();
        RotacionaZ = new javax.swing.JButton();
        RotZ = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ImagemPanel.setBackground(new java.awt.Color(200, 200, 200));
        ImagemPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ImagemPanelMouseMoved(evt);
            }
        });

        ImagemLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ImagemLabelMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout ImagemPanelLayout = new javax.swing.GroupLayout(ImagemPanel);
        ImagemPanel.setLayout(ImagemPanelLayout);
        ImagemPanelLayout.setHorizontalGroup(
            ImagemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImagemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );
        ImagemPanelLayout.setVerticalGroup(
            ImagemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImagemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
        );

        PosLabel.setText("(0,0)");

        FrontalButton.setText("Projeção Frontal");
        FrontalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrontalButtonActionPerformed(evt);
            }
        });

        CavButton.setText("Projecao Cabinet");
        CavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CavButtonActionPerformed(evt);
            }
        });

        anguloText.setText("45");
        anguloText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anguloTextActionPerformed(evt);
            }
        });

        EscalaButton.setText("Escala");
        EscalaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscalaButtonActionPerformed(evt);
            }
        });

        EscalaX.setText("1");

        EscalaY.setText("1");

        EscalaZ.setText("1");

        RotacionaX.setText("Rotaciona X");
        RotacionaX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotacionaXActionPerformed(evt);
            }
        });

        RotX.setText("0");

        RotY.setText("0");

        RotacionaY.setText("Rotaciona Y");
        RotacionaY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotacionaYActionPerformed(evt);
            }
        });

        RotacionaZ.setText("Rotaciona Z");
        RotacionaZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotacionaZActionPerformed(evt);
            }
        });

        RotZ.setText("0");
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PosLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FrontalButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CavButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anguloText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EscalaButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EscalaX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EscalaY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EscalaZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RotacionaX)
                                    .addComponent(RotacionaY)
                                    .addComponent(RotacionaZ))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RotY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RotX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RotZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImagemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FrontalButton)
                    .addComponent(EscalaButton)
                    .addComponent(EscalaX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EscalaY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EscalaZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CavButton)
                    .addComponent(anguloText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RotacionaX)
                    .addComponent(RotX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RotY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RotacionaY))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RotacionaZ)
                    .addComponent(RotZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(PosLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImagemLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagemLabelMouseMoved
        // TODO add your handling code here:
        Point p = ImagemLabel.getMousePosition();
        PosLabel.setText("(" + Math.round(p.getX()) + "," + Math.round(p.getY()) + ")");
    }//GEN-LAST:event_ImagemLabelMouseMoved

    private void ImagemPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagemPanelMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ImagemPanelMouseMoved

    private void FrontalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrontalButtonActionPerformed
        // TODO add your handling code here:
        ImagemLabel.setIcon(new ImageIcon(casa.projecaoFrontal()));
    }//GEN-LAST:event_FrontalButtonActionPerformed

    private void CavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CavButtonActionPerformed
        // TODO add your handling code here:
        ImagemLabel.setIcon(new ImageIcon(casa.projecaoCaveira(Integer.parseInt(anguloText.getText()))));
    }//GEN-LAST:event_CavButtonActionPerformed

    private void anguloTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anguloTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anguloTextActionPerformed

    private void EscalaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscalaButtonActionPerformed
        // TODO add your handling code here:
        double novox,novoy,novoz;
        novox = Double.parseDouble(EscalaX.getText());
        novoy = Double.parseDouble(EscalaY.getText());
        novoz = Double.parseDouble(EscalaZ.getText());
        casa.escala(novox, novoy, novoz);
        ImagemLabel.setIcon(new ImageIcon(casa.projecaoCaveira(Integer.parseInt(anguloText.getText()))));
    }//GEN-LAST:event_EscalaButtonActionPerformed

    private void RotacionaXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RotacionaXActionPerformed
        // TODO add your handling code here:
        casa.rotacionaX(Double.parseDouble(RotX.getText()));
        ImagemLabel.setIcon(new ImageIcon(casa.projecaoCaveira(Integer.parseInt(anguloText.getText()))));
    }//GEN-LAST:event_RotacionaXActionPerformed

    private void RotacionaYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RotacionaYActionPerformed
        // TODO add your handling code here:
        casa.rotacionaY(Double.parseDouble(RotY.getText()));
        ImagemLabel.setIcon(new ImageIcon(casa.projecaoCaveira(Integer.parseInt(anguloText.getText()))));
    }//GEN-LAST:event_RotacionaYActionPerformed

    private void RotacionaZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RotacionaZActionPerformed
        // TODO add your handling code here:
        casa.rotacionaZ(Double.parseDouble(RotZ.getText()));
        ImagemLabel.setIcon(new ImageIcon(casa.projecaoCaveira(Integer.parseInt(anguloText.getText()))));
    }//GEN-LAST:event_RotacionaZActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visualizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Visualizador().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CavButton;
    private javax.swing.JButton EscalaButton;
    private javax.swing.JTextField EscalaX;
    private javax.swing.JTextField EscalaY;
    private javax.swing.JTextField EscalaZ;
    private javax.swing.JButton FrontalButton;
    private javax.swing.JLabel ImagemLabel;
    private javax.swing.JPanel ImagemPanel;
    private javax.swing.JLabel PosLabel;
    private javax.swing.JTextField RotX;
    private javax.swing.JTextField RotY;
    private javax.swing.JTextField RotZ;
    private javax.swing.JButton RotacionaX;
    private javax.swing.JButton RotacionaY;
    private javax.swing.JButton RotacionaZ;
    private javax.swing.JTextField anguloText;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
