package trabalhopratico1;

import java.awt.Point;
import java.awt.image.BufferedImage;
import java.awt.image.ColorModel;
import java.awt.image.WritableRaster;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author gabrielozaki
 */
public class Visualizador extends javax.swing.JFrame {
    //Imagem a ser manipulada
    BufferedImage imagem;
    //Cópia da imagem original, para podermos restaurar
    BufferedImage original;
    //Pontos da reta
    Point ini;
    Point fim;
    //Verifica se é o primeiro ponto da reta
    boolean primeiroClick = true;
    //Verifica se vai desenhar uma reta ou ponto
    boolean retaponto = false;
    //Classe de algoritmos
    Algoritmos a = new Algoritmos();

    /**
     * Creates new form visualizador
     */
    public Visualizador() {
        initComponents();
    }

    //Copia uma BufferedImage, evitando assim que editemos a imagem original
    //Código de referencia veio daqui:
    //http://stackoverflow.com/questions/3514158/how-do-you-clone-a-bufferedimage
    static BufferedImage clonaImagem(BufferedImage original) {
        //Pega o model das cores
        ColorModel cm = original.getColorModel();
        //Verifica se existe transparencia
        boolean isAlphaPremultiplied = cm.isAlphaPremultiplied();
        //Copia os dados da imagem
        WritableRaster raster = original.copyData(null);
        //retorna a imagem
        return new BufferedImage(cm, raster, isAlphaPremultiplied, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImagemPanel = new javax.swing.JPanel();
        ImagemLabel = new javax.swing.JLabel();
        PosLabel = new javax.swing.JLabel();
        PontoButton = new javax.swing.JRadioButton();
        RetaButton = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AbrirMenu = new javax.swing.JMenuItem();
        AcaoMenu = new javax.swing.JMenu();
        OriginalMenu = new javax.swing.JMenuItem();
        CinzaMenu = new javax.swing.JMenuItem();
        InverterMenu = new javax.swing.JMenuItem();
        SeparaMenu = new javax.swing.JMenu();
        VermelhoMenu = new javax.swing.JMenuItem();
        VerdeMenu = new javax.swing.JMenuItem();
        AzulMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ImagemPanel.setBackground(new java.awt.Color(200, 200, 200));
        ImagemPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ImagemPanelMouseMoved(evt);
            }
        });

        ImagemLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ImagemLabelMouseMoved(evt);
            }
        });
        ImagemLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagemLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ImagemPanelLayout = new javax.swing.GroupLayout(ImagemPanel);
        ImagemPanel.setLayout(ImagemPanelLayout);
        ImagemPanelLayout.setHorizontalGroup(
            ImagemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImagemLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ImagemPanelLayout.setVerticalGroup(
            ImagemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImagemLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PosLabel.setText("(0,0)");

        PontoButton.setSelected(true);
        PontoButton.setText("Ponto");
        PontoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PontoButtonActionPerformed(evt);
            }
        });

        RetaButton.setText("Reta");
        RetaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetaButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("Arquivo");

        AbrirMenu.setText("Abrir");
        AbrirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirMenuActionPerformed(evt);
            }
        });
        jMenu1.add(AbrirMenu);

        jMenuBar1.add(jMenu1);

        AcaoMenu.setText("Ações");

        OriginalMenu.setText("Original");
        OriginalMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OriginalMenuActionPerformed(evt);
            }
        });
        AcaoMenu.add(OriginalMenu);

        CinzaMenu.setText("Obter Tons de Cinza");
        CinzaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CinzaMenuActionPerformed(evt);
            }
        });
        AcaoMenu.add(CinzaMenu);

        InverterMenu.setText("Inverter Cores");
        InverterMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InverterMenuActionPerformed(evt);
            }
        });
        AcaoMenu.add(InverterMenu);

        SeparaMenu.setText("Separar Canais");

        VermelhoMenu.setText("Apenas Canal Vemelho");
        VermelhoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VermelhoMenuActionPerformed(evt);
            }
        });
        SeparaMenu.add(VermelhoMenu);

        VerdeMenu.setText("Apenas Canal Verde");
        VerdeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerdeMenuActionPerformed(evt);
            }
        });
        SeparaMenu.add(VerdeMenu);

        AzulMenu.setText("Apenas Canal Azul");
        AzulMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AzulMenuActionPerformed(evt);
            }
        });
        SeparaMenu.add(AzulMenu);

        AcaoMenu.add(SeparaMenu);

        jMenuBar1.add(AcaoMenu);
        AcaoMenu.setVisible(false);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PosLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PontoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RetaButton)))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(ImagemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PontoButton)
                    .addComponent(RetaButton)
                    .addComponent(PosLabel))
                .addContainerGap(298, Short.MAX_VALUE))
        );

        PosLabel.setVisible(false);
        PontoButton.setVisible(false);
        RetaButton.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AbrirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirMenuActionPerformed
        // TODO add your handling code here:
        //Foi escolhido o CTRL+O como atalho porque o CTRL+A selecionava todo texto da TextArea
        // Explorador de arquivos do Java, exemplo veio do site da oracle
        JFileChooser fc = new JFileChooser();
        //Faz ele abrir inicialmente na pasta do projeto
        fc.setCurrentDirectory(new java.io.File("."));
        //Abre o explorador
        int returnVal = fc.showOpenDialog(Visualizador.this);
        //Se foi clicado no abrir arquivo
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            //Pega o arquivo selecionado
            File file = fc.getSelectedFile();
            try {
                //Abre a imagem
                this.imagem = ImageIO.read(file);
                this.original = clonaImagem(this.imagem);
                //Transforma em um icon pra gente passar para o jlabel
                ImageIcon imagemIcon = new ImageIcon(this.imagem);
                //Coloca no jlabel
                this.setSize(this.imagem.getWidth() + 150, this.imagem.getHeight() + 150);
                ImagemPanel.setSize(this.imagem.getWidth(), this.imagem.getHeight());
                ImagemLabel.setSize(this.imagem.getWidth(), this.imagem.getHeight());
                ImagemLabel.setIcon(imagemIcon);
                PosLabel.setVisible(true);
                PontoButton.setVisible(true);
                RetaButton.setVisible(true);
                AcaoMenu.setVisible(true);
                //imagemPanel.setSize(imagemPanel.getWidth(), imagemPanel.getHeight());

            } catch (IOException ex) {
                Logger.getLogger(Visualizador.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_AbrirMenuActionPerformed

    private void CinzaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CinzaMenuActionPerformed
        // TODO add your handling code here:
        //Insere no label
        //ImagemLabel.setIcon(new ImageIcon(a.cinzaMedia(this.imagem)));
        ImagemLabel.setIcon(new ImageIcon(a.cinzaLuminecencia(this.imagem)));


    }//GEN-LAST:event_CinzaMenuActionPerformed

    private void InverterMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InverterMenuActionPerformed
        // TODO add your handling code here:
        //Insere no label
        ImagemLabel.setIcon(new ImageIcon(a.inverteCores(this.imagem)));

    }//GEN-LAST:event_InverterMenuActionPerformed

    private void OriginalMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OriginalMenuActionPerformed
        // TODO add your handling code here:
        //Aqui usamos o ImagemLabel pq o panel muda de tamanho
        this.imagem = clonaImagem(original);
        ImagemLabel.setIcon(new ImageIcon(this.imagem));

    }//GEN-LAST:event_OriginalMenuActionPerformed

    private void VermelhoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VermelhoMenuActionPerformed
        //Insere no label
        ImagemLabel.setIcon(new ImageIcon(a.separaCanal(this.imagem, "Vermelho")));
    }//GEN-LAST:event_VermelhoMenuActionPerformed

    private void VerdeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerdeMenuActionPerformed
        //Insere no label
        ImagemLabel.setIcon(new ImageIcon(a.separaCanal(this.imagem, "Verde")));
    }//GEN-LAST:event_VerdeMenuActionPerformed

    private void AzulMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AzulMenuActionPerformed
        //Insere no label
        ImagemLabel.setIcon(new ImageIcon(a.separaCanal(this.imagem, "Azul")));
    }//GEN-LAST:event_AzulMenuActionPerformed

    private void ImagemPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagemPanelMouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_ImagemPanelMouseMoved

    private void ImagemLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagemLabelMouseClicked
        // TODO add your handling code here:
        if (retaponto == false) {
            //Insere ponto no label
            ImagemLabel.setIcon(new ImageIcon(a.desenhaPonto(this.imagem, ImagemPanel.getMousePosition())));

        } else if (this.primeiroClick == true) {
            //Marca que ocorreu o primeiro clique
            this.primeiroClick = false;
            this.ini = ImagemLabel.getMousePosition();
            System.out.println("Primeiro clique:" + this.ini.getX() + "," + this.ini.getY());

        } else {
            //Marca que o primeiro clique deve ser marcado de novo
            this.primeiroClick = true;
            this.fim = ImagemLabel.getMousePosition();
            System.out.println("Segundo clique:" + this.fim.getX() + "," + this.fim.getY());

            //Insere no label
            //ImagemLabel.setIcon(new ImageIcon(a.desenhaRetaParametrica(this.imagem,this.ini,this.fim,1000)));
            ImagemLabel.setIcon(new ImageIcon(a.desenhaRetaBresenham(this.imagem, this.ini, this.fim)));

        }


    }//GEN-LAST:event_ImagemLabelMouseClicked

    private void ImagemLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagemLabelMouseMoved
        // TODO add your handling code here:
        Point p = ImagemLabel.getMousePosition();
        PosLabel.setText("(" + Math.round(p.getX()) + "," + Math.round(p.getY()) + ")");
    }//GEN-LAST:event_ImagemLabelMouseMoved

    private void PontoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PontoButtonActionPerformed
        // TODO add your handling code here:
        this.retaponto = false;
        RetaButton.setSelected(false);
    }//GEN-LAST:event_PontoButtonActionPerformed

    private void RetaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetaButtonActionPerformed
        // TODO add your handling code here:
        this.retaponto = true;
        PontoButton.setSelected(false);
    }//GEN-LAST:event_RetaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visualizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Visualizador().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AbrirMenu;
    private javax.swing.JMenu AcaoMenu;
    private javax.swing.JMenuItem AzulMenu;
    private javax.swing.JMenuItem CinzaMenu;
    private javax.swing.JLabel ImagemLabel;
    private javax.swing.JPanel ImagemPanel;
    private javax.swing.JMenuItem InverterMenu;
    private javax.swing.JMenuItem OriginalMenu;
    private javax.swing.JRadioButton PontoButton;
    private javax.swing.JLabel PosLabel;
    private javax.swing.JRadioButton RetaButton;
    private javax.swing.JMenu SeparaMenu;
    private javax.swing.JMenuItem VerdeMenu;
    private javax.swing.JMenuItem VermelhoMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
